<?php /* Smarty version 2.6.25, created on 2010-07-16 18:42:45
         compiled from tpl_head:22 */

$this->_cache_serials['/home/.mueller/cwinchell/winchelldesign.com/iGnition/BACKEND6/tmp/templates_c/%%19^194^194941AA%%tpl_head%3A22.inc'] = '1a6f2649dbcc83bc65d315b047eeb018';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'title', 'tpl_head:22', 4, false),array('function', 'sitename', 'tpl_head:22', 4, false),array('function', 'metadata', 'tpl_head:22', 7, false),array('function', 'cms_stylesheet', 'tpl_head:22', 10, false),array('function', 'cms_selflink', 'tpl_head:22', 13, false),)), $this); ?>
<?php
function _smarty_tplfunc_1a6f2649dbcc83bc65d315b047eeb018_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1a6f2649dbcc83bc65d315b047eeb018','0');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_1a6f2649dbcc83bc65d315b047eeb018_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1a6f2649dbcc83bc65d315b047eeb018','1');echo smarty_cms_function_sitename(array(), $_smarty);
}


function _smarty_tplfunc_1a6f2649dbcc83bc65d315b047eeb018_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1a6f2649dbcc83bc65d315b047eeb018','2');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_1a6f2649dbcc83bc65d315b047eeb018_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1a6f2649dbcc83bc65d315b047eeb018','3');echo smarty_cms_function_cms_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_1a6f2649dbcc83bc65d315b047eeb018_4(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1a6f2649dbcc83bc65d315b047eeb018','4');echo smarty_cms_function_cms_selflink(array('dir' => 'start','rellink' => 1), $_smarty);
}


function _smarty_tplfunc_1a6f2649dbcc83bc65d315b047eeb018_5(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1a6f2649dbcc83bc65d315b047eeb018','5');echo smarty_cms_function_cms_selflink(array('dir' => 'prev','rellink' => 1), $_smarty);
}


function _smarty_tplfunc_1a6f2649dbcc83bc65d315b047eeb018_6(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('1a6f2649dbcc83bc65d315b047eeb018','6');echo smarty_cms_function_cms_selflink(array('dir' => 'next','rellink' => 1), $_smarty);
}



?>
