<?php /* Smarty version 2.6.25, created on 2010-07-16 15:16:31
         compiled from install7.tpl */

$this->_cache_serials['/home/.mueller/cwinchell/winchelldesign.com/iGnition/BACKEND6/tmp/templates_c/%%38^38F^38F3E08D%%install7.tpl.inc'] = 'e576042823e4f63f45161272b2390503';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'lang_install', 'install7.tpl', 8, false),)), $this); ?>
<?php
function _smarty_tplfunc_e576042823e4f63f45161272b2390503_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('e576042823e4f63f45161272b2390503','0');echo smarty_lang(array('a' => 'install_admin_tablesnotcreated'), $_smarty);
}


function _smarty_tplfunc_e576042823e4f63f45161272b2390503_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('e576042823e4f63f45161272b2390503','1');echo smarty_lang(array('a' => 'install_admin_congratulations'), $_smarty);
}


function _smarty_tplfunc_e576042823e4f63f45161272b2390503_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('e576042823e4f63f45161272b2390503','2');echo smarty_lang(array('a' => 'go_to_admin'), $_smarty);
}



?>
