<?php /* Smarty version 2.6.25, created on 2010-07-16 18:42:44
         compiled from tpl_top:22 */

$this->_cache_serials['/home/.mueller/cwinchell/winchelldesign.com/iGnition/BACKEND6/tmp/templates_c/%%52^52E^52E7C88B%%tpl_top%3A22.inc'] = '10d0fb6f0e9784a35f91bf36a4df0d0d';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'process_pagedata', 'tpl_top:22', 1, false),)), $this); ?>
<?php
function _smarty_tplfunc_10d0fb6f0e9784a35f91bf36a4df0d0d_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('10d0fb6f0e9784a35f91bf36a4df0d0d','0');echo smarty_cms_function_process_pagedata(array(), $_smarty);
}



?>
