<?php /* Smarty version 2.6.25, created on 2010-07-16 18:42:45
         compiled from globalcontent:footer */

$this->_cache_serials['/home/.mueller/cwinchell/winchelldesign.com/iGnition/BACKEND6/tmp/templates_c/%%EE^EE6^EE6D73C2%%globalcontent%3Afooter.inc'] = 'b2ec0c4b42a6df6cae2242ccc28faf08';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'custom_copyright', 'globalcontent:footer', 1, false),array('function', 'cms_version', 'globalcontent:footer', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_b2ec0c4b42a6df6cae2242ccc28faf08_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b2ec0c4b42a6df6cae2242ccc28faf08','0');echo cms_tmp_custom_copyright_userplugin_function(array(), $_smarty);
}


function _smarty_tplfunc_b2ec0c4b42a6df6cae2242ccc28faf08_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('b2ec0c4b42a6df6cae2242ccc28faf08','1');echo smarty_cms_function_cms_version(array(), $_smarty);
}



?>
