<?php /* Smarty version 2.6.25, created on 2010-07-16 18:42:45
         compiled from module_file_tpl:MenuManager%3Bcssmenu_ulshadow.tpl */

$this->_cache_serials['/home/.mueller/cwinchell/winchelldesign.com/iGnition/BACKEND6/tmp/templates_c/9bd2144b7dae121c1ab674f5b38919cf^%%2D^2D2^2D22AD26%%module_file_tpl%3AMenuManager%3Bcssmenu_ulshadow.tpl.inc'] = 'dca76e2df6f2b20989ef4476d2e0aad7';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'repeat', 'module_file_tpl:MenuManager;cssmenu_ulshadow.tpl', 11, false),)), $this); ?>
<?php
function _smarty_tplfunc_dca76e2df6f2b20989ef4476d2e0aad7_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('dca76e2df6f2b20989ef4476d2e0aad7','0');echo smarty_cms_function_repeat(array('string' => '<ul class="unli">','times' => $_smarty->_tpl_vars['node']->depth-$_smarty->_tpl_vars['node']->prevdepth), $_smarty);
}


function _smarty_tplfunc_dca76e2df6f2b20989ef4476d2e0aad7_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('dca76e2df6f2b20989ef4476d2e0aad7','1');echo smarty_cms_function_repeat(array('string' => '</li><li class="separator once" style="list-style-type: none;">&nbsp;</li></ul>','times' => $_smarty->_tpl_vars['node']->prevdepth-$_smarty->_tpl_vars['node']->depth), $_smarty);
}


function _smarty_tplfunc_dca76e2df6f2b20989ef4476d2e0aad7_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('dca76e2df6f2b20989ef4476d2e0aad7','2');echo smarty_cms_function_repeat(array('string' => '</li><li class="separator once" style="list-style-type: none;">&nbsp;</li></ul>','times' => $_smarty->_tpl_vars['node']->depth-1), $_smarty);
}



?>
